[project]
name = "polaris-common-core"
version = "0.1.0"
description = "python项目开发通用工具包"

authors = [
    {name = "tony",email = "tony1@kinwong.com"}
]

readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "requests (>=2.32.5,<3.0.0)"
]

[tool.poetry]
packages = [{include = "polaris_common_core", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
