[project]
name = "polaris-common-core"
version = "1.1.2"
description = "北极星python项目开发通用工具包"

authors = [
    {name = "tony",email = "luojie_dataops@126.com"}
]

readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "requests (>=2.32.5,<3.0.0)"
]

[tool.poetry]
packages = [
    {include = "polaris_common_core", from = "src"},
#    {include = "ai", from = "src"},
#    {include = "api", from = "src"},
#    {include = "commom", from = "src"},
#    {include = "connector", from = "src"},
#    {include = "crypto", from = "src"},
#    {include = "enums", from = "src"},
#    {include = "exception", from = "src"},
    {include = "polaris_logger", from = "src"},
#    {include = "message", from = "src"},
#    {include = "mq", from = "src"},
#    {include = "pyspark", from = "src"},
#    {include = "pyflink", from = "src"}
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
